#!/bin/bash

# Copyright (C) 2002  MMM
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 59
# Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# Note:
# - Spaces are not allowed inside class names
#
# Concepts:
# - Dir  = e.g. fi/mmm/utils
# - Java = e.g. fi/mmm/utils/Strings.java
#
# - Pkg  = e.g. fi.mmm.utils
# - Cl   = Qcl | Ucl
# - Qcl  = e.g. fi.mmm.utils.Strings
# - Ucl  = e.g. Strings

source grep-and-sed-functions

export idPrefixPat='\([^a-zA-Z0-9_.]\)'
export idSuffixPat='\([^a-zA-Z0-9_]\)'
export wsPat=$'[\t ][\t ]*'
export importClPat=$'^[ \t]*import[ \t][ \t]*[a-zA-Z0-9_.]*[ \t]*;'

function strip-spaces-from { sed-from "$1" 's#'$wsPat'##g' ; }

function dir-of-pkg { sed-from "$1" 's#\.#/#g' ; }
function pkg-of-dir { sed-from "$1" 's#/#.#g' ; }
function java-of-cl { echo $(dir-of-pkg "$1").java ; }
function cl-of-java { sed-from "$1" -e 's#\.java##g' -e 's#/#.#g' -e 's#^\.##g' -e 's#^/##g' ; }

function ucl-of-qcl { sed-from "$1" 's#.*\.##g' ; }
function pkg-of-qcl { sed-from "$1" 's#\.[^.]*$##g' ; }
