#!/bin/bash

if test "$1" = "--help" ; then
    echo \
"Usage: $(echo $0 | sed 's#.*/##g')

1. Removes all generated/compiled files of the project.
2. Builds everything.
3. Runs all tests.

Requires project-info."
    exit
fi

source javautils-project-info

javautils-clean && \
javautils-build-and-test
