#!/bin/bash

# Copyright (C) 2002  MMM
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 59
# Temple Place - Suite 330, Boston, MA  02111-1307, USA.

source grep-and-sed-functions

if test "$#" -lt 4 ; then
    echo 'Usage: replace <pattern> <separator> <replacement> <file> ...

Replaces the pattern in each file with the replacement. The patterns and
replacements are the same as accepted by grep & sed.'
    exit
fi

grepPat="${1}"
sedPat="s${2}${1}${2}${3}${2}g"

shift 3

for f in $(grep -l -e "$grepPat" "$@") ; do
    replace-in-file "$f" -e "$sedPat"
done
