package javautils.maps;

import java.util.Map;
import javautils.holders.BooleanHolder;


/**
 * <p>Map from objects to boolean-values. {@link BooleanHolder}-objects are
 * used for storing the values in the map.</p>
 */
public final class ObjectToBooleanMap extends AbstractTypedMap {

  // Warning: This file was generated by the javautils-create-primitive-typed-map
  // script. It is probably more productive to extend the script rather
  // than edit this code directly.

  /**
   * <p>A new map based on the map type used by {@link
   * AbstractTypedMap#AbstractTypedMap}.</p>
   */
  public ObjectToBooleanMap() {}

  /**
   * <p>A new <code>Object->boolean</code> map using the given map. The
   * given map must not contain any values that are not {@link
   * BooleanHolder}-objects. The given map should also never be modified
   * except by using the services of this class.</p>
   */
  public ObjectToBooleanMap(Map map) {
    super(map);
  }

  /**
   * <p>Tests that the value is a non <code>null</code> {@link
   * BooleanHolder}-object.</p>
   */
  protected boolean valuePredicate(Object value) {
    return null != value && value instanceof BooleanHolder;
  }

  /**
   * <p>Associates the key with the specified value. Will not create a new
   * holder if the key is already associated with a value.</p>
   */
  public void put(Object key, boolean value) {
    BooleanHolder holder = holder(key);

    if (null == holder)
      put(key, new BooleanHolder(value));
    else
      holder.value = value;
  }

  /**
   * <p>Associates the key with the specified holder.</p>
   */
  public void put(Object key, BooleanHolder holder) {
    assert null != holder;
    map.put(key, holder);
  }

  /**
   * <p>The value associated with the key - throws an assertion exception
   * if the key is not associated with a value.</p>
   */
  public boolean get(Object key) {
    return ref(key).value;
  }

  /**
   * <p>The value associated with the key <i>or</i> the specified
   * alternative value if the key is not associated with any value.</p>
   */
  public boolean getOr(Object key, boolean alternative) {
    BooleanHolder result = holder(key);
    return null != result ? result.value : alternative;
  }

  /**
   * <p>The holder associated with the key - throws an assertion exception
   * if the key is not associated with a value.</p>
   */
  public BooleanHolder ref(Object key) {
    BooleanHolder holder = holder(key);
    assert null != holder;
    return holder;
  }

  /**
   * <p>The holder associated with the key or a new holder that holds the
   * specified value and associated with the key.</p>
   */
  public BooleanHolder refOr(Object key, boolean value) {
    BooleanHolder holder = holder(key);
    if (null == holder) {
      holder = new BooleanHolder(value);
      map.put(key, holder);
    }
    return holder;
  }

  /**
   * <p>The holder of the value associated with the key or null if the key
   * is not associated with a value.</p>
   */
  public BooleanHolder holder(Object key) {
    return (BooleanHolder)map.get(key);
  }
}
